version: '3.8'
services:
  exporter:
    image: shalb/docker_exporter:0.0.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9647:9647"
